name: deploy
on:
  push:
    branches:
      - main
jobs:
  new-version-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build dist folder
        run: |
          mkdir -p dist
          rsync -r --exclude 'dist' --exclude '.git' --exclude '.github' --exclude '.gitignore' . dist
      - name: Deploy with rsync
        env:
          remote_host: ${{ secrets.CLOUDWAYS_HOST }}
          remote_port: "22"
          remote_user: ${{ secrets.CLOUDWAYS_USER }}
          remote_key: ${{ secrets.CLOUDWAYS_SSH_PRIVATE_KEY }}
          local_dir: "dist/"
          remote_dir: ${{ secrets.CLOUDWAYS_PATH }}
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          rsync -avzr -e "ssh -p ${remote_port} -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
